// autoImport.ts
// This file was generated by ts-java.
/// <reference path="java.d.ts" />

import java = require('java');

export = autoImport;

interface Dictionary {
  [index: string]: string;
}

function autoImport(shortName: 'GlobFunction'): Java.co.redseal.gremlinnode.function_.GlobFunction.Static;
function autoImport(shortName: 'GroovyLambda'): Java.co.redseal.gremlinnode.function_.GroovyLambda.Static;
function autoImport(shortName: 'TestClass'): Java.co.redseal.gremlinnode.testing.TestClass.Static;
function autoImport(shortName: 'StringInputStream'): Java.co.redseal.util.StringInputStream.Static;
function autoImport(shortName: 'Binding'): Java.groovy.lang.Binding.Static;
function autoImport(shortName: 'Closure'): Java.groovy.lang.Closure.Static;
function autoImport(shortName: 'DelegatingMetaClass'): Java.groovy.lang.DelegatingMetaClass.Static;
function autoImport(shortName: 'GroovyClassLoader'): Java.groovy.lang.GroovyClassLoader.Static;
function autoImport(shortName: 'GroovyCodeSource'): Java.groovy.lang.GroovyCodeSource.Static;
function autoImport(shortName: 'GroovyObjectSupport'): Java.groovy.lang.GroovyObjectSupport.Static;
function autoImport(shortName: 'GroovyResourceLoader'): Java.groovy.lang.GroovyResourceLoader.Static;
function autoImport(shortName: 'IntRange'): Java.groovy.lang.IntRange.Static;
function autoImport(shortName: 'MetaBeanProperty'): Java.groovy.lang.MetaBeanProperty.Static;
function autoImport(shortName: 'MetaClass'): Java.groovy.lang.MetaClass.Static;
function autoImport(shortName: 'MetaMethod'): Java.groovy.lang.MetaMethod.Static;
function autoImport(shortName: 'MetaProperty'): Java.groovy.lang.MetaProperty.Static;
function autoImport(shortName: 'Range'): Java.groovy.lang.Range.Static;
function autoImport(shortName: 'Reference'): Java.groovy.lang.Reference.Static;
function autoImport(shortName: 'ByteArrayOutputStream'): Java.java.io.ByteArrayOutputStream.Static;
function autoImport(shortName: 'FileInputStream'): Java.java.io.FileInputStream.Static;
function autoImport(shortName: 'FileOutputStream'): Java.java.io.FileOutputStream.Static;
function autoImport(shortName: 'InputStream'): Java.java.io.InputStream.Static;
function autoImport(shortName: 'OutputStream'): Java.java.io.OutputStream.Static;
function autoImport(shortName: 'Boolean'): Java.java.lang.Boolean.Static;
function autoImport(shortName: 'Class'): Java.java.lang.Class.Static;
function autoImport(shortName: 'ClassLoader'): Java.java.lang.ClassLoader.Static;
function autoImport(shortName: 'Double'): Java.java.lang.Double.Static;
function autoImport(shortName: 'Enum'): Java.java.lang.Enum.Static;
function autoImport(shortName: 'Float'): Java.java.lang.Float.Static;
function autoImport(shortName: 'Integer'): Java.java.lang.Integer.Static;
function autoImport(shortName: 'Iterable'): Java.java.lang.Iterable.Static;
function autoImport(shortName: 'Long'): Java.java.lang.Long.Static;
function autoImport(shortName: 'Object'): Java.java.lang.Object.Static;
function autoImport(shortName: 'Array'): Java.java.lang.reflect.Array.Static;
function autoImport(shortName: 'Short'): Java.java.lang.Short.Static;
function autoImport(shortName: 'String'): Java.java.lang.String.Static;
function autoImport(shortName: 'Charset'): Java.java.nio.charset.Charset.Static;
function autoImport(shortName: 'StandardCharsets'): Java.java.nio.charset.StandardCharsets.Static;
function autoImport(shortName: 'AbstractCollection'): Java.java.util.AbstractCollection.Static;
function autoImport(shortName: 'AbstractList'): Java.java.util.AbstractList.Static;
function autoImport(shortName: 'AbstractMap'): Java.java.util.AbstractMap.Static;
function autoImport(shortName: 'AbstractSet'): Java.java.util.AbstractSet.Static;
function autoImport(shortName: 'ArrayList'): Java.java.util.ArrayList.Static;
function autoImport(shortName: 'Collection'): Java.java.util.Collection.Static;
function autoImport(shortName: 'Comparator'): Java.java.util.Comparator.Static;
function autoImport(shortName: 'BiConsumer'): Java.java.util.function_.BiConsumer.Static;
function autoImport(shortName: 'BiFunction'): Java.java.util.function_.BiFunction.Static;
function autoImport(shortName: 'BinaryOperator'): Java.java.util.function_.BinaryOperator.Static;
function autoImport(shortName: 'BiPredicate'): Java.java.util.function_.BiPredicate.Static;
function autoImport(shortName: 'Consumer'): Java.java.util.function_.Consumer.Static;
function autoImport(shortName: 'Function'): Java.java.util.function_.Function.Static;
function autoImport(shortName: 'Predicate'): Java.java.util.function_.Predicate.Static;
function autoImport(shortName: 'Supplier'): Java.java.util.function_.Supplier.Static;
function autoImport(shortName: 'UnaryOperator'): Java.java.util.function_.UnaryOperator.Static;
function autoImport(shortName: 'HashMap'): Java.java.util.HashMap.Static;
function autoImport(shortName: 'HashSet'): Java.java.util.HashSet.Static;
function autoImport(shortName: 'Iterator'): Java.java.util.Iterator.Static;
function autoImport(shortName: 'LinkedHashMap'): Java.java.util.LinkedHashMap.Static;
function autoImport(shortName: 'List'): Java.java.util.List.Static;
function autoImport(shortName: 'ListIterator'): Java.java.util.ListIterator.Static;
function autoImport(shortName: 'Map'): Java.java.util.Map.Static;
function autoImport(shortName: 'Map$Entry'): Java.java.util.Map$Entry.Static;
function autoImport(shortName: 'NoSuchElementException'): Java.java.util.NoSuchElementException.Static;
function autoImport(shortName: 'Set'): Java.java.util.Set.Static;
function autoImport(shortName: 'AbstractScriptEngine'): Java.javax.script.AbstractScriptEngine.Static;
function autoImport(shortName: 'Bindings'): Java.javax.script.Bindings.Static;
function autoImport(shortName: 'CompiledScript'): Java.javax.script.CompiledScript.Static;
function autoImport(shortName: 'ScriptContext'): Java.javax.script.ScriptContext.Static;
function autoImport(shortName: 'ScriptEngine'): Java.javax.script.ScriptEngine.Static;
function autoImport(shortName: 'ScriptEngineFactory'): Java.javax.script.ScriptEngineFactory.Static;
function autoImport(shortName: 'GComparator'): Java.org.apache.tinkerpop.gremlin.groovy.function_.GComparator.Static;
function autoImport(shortName: 'GFunction'): Java.org.apache.tinkerpop.gremlin.groovy.function_.GFunction.Static;
function autoImport(shortName: 'GSupplier'): Java.org.apache.tinkerpop.gremlin.groovy.function_.GSupplier.Static;
function autoImport(shortName: 'GUnaryOperator'): Java.org.apache.tinkerpop.gremlin.groovy.function_.GUnaryOperator.Static;
function autoImport(shortName: 'GremlinGroovyScriptEngine'): Java.org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.Static;
function autoImport(shortName: 'ClusterCountMapReduce'): Java.org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.ClusterCountMapReduce.Static;
function autoImport(shortName: 'ClusterCountMapReduce$Builder'): Java.org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.ClusterCountMapReduce$Builder.Static;
function autoImport(shortName: 'ClusterPopulationMapReduce'): Java.org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.ClusterPopulationMapReduce.Static;
function autoImport(shortName: 'ClusterPopulationMapReduce$Builder'): Java.org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.ClusterPopulationMapReduce$Builder.Static;
function autoImport(shortName: 'PeerPressureVertexProgram'): Java.org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.PeerPressureVertexProgram.Static;
function autoImport(shortName: 'PeerPressureVertexProgram$Builder'): Java.org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.PeerPressureVertexProgram$Builder.Static;
function autoImport(shortName: 'ComputerResult'): Java.org.apache.tinkerpop.gremlin.process.computer.ComputerResult.Static;
function autoImport(shortName: 'GraphComputer'): Java.org.apache.tinkerpop.gremlin.process.computer.GraphComputer.Static;
function autoImport(shortName: 'GraphComputer$Exceptions'): Java.org.apache.tinkerpop.gremlin.process.computer.GraphComputer$Exceptions.Static;
function autoImport(shortName: 'GraphComputer$Features'): Java.org.apache.tinkerpop.gremlin.process.computer.GraphComputer$Features.Static;
function autoImport(shortName: 'GraphComputer$Isolation'): Java.org.apache.tinkerpop.gremlin.process.computer.GraphComputer$Isolation.Static;
function autoImport(shortName: 'GraphComputer$Persist'): Java.org.apache.tinkerpop.gremlin.process.computer.GraphComputer$Persist.Static;
function autoImport(shortName: 'GraphComputer$ResultGraph'): Java.org.apache.tinkerpop.gremlin.process.computer.GraphComputer$ResultGraph.Static;
function autoImport(shortName: 'KeyValue'): Java.org.apache.tinkerpop.gremlin.process.computer.KeyValue.Static;
function autoImport(shortName: 'MapReduce'): Java.org.apache.tinkerpop.gremlin.process.computer.MapReduce.Static;
function autoImport(shortName: 'MapReduce$MapEmitter'): Java.org.apache.tinkerpop.gremlin.process.computer.MapReduce$MapEmitter.Static;
function autoImport(shortName: 'MapReduce$NullObject'): Java.org.apache.tinkerpop.gremlin.process.computer.MapReduce$NullObject.Static;
function autoImport(shortName: 'MapReduce$ReduceEmitter'): Java.org.apache.tinkerpop.gremlin.process.computer.MapReduce$ReduceEmitter.Static;
function autoImport(shortName: 'MapReduce$Stage'): Java.org.apache.tinkerpop.gremlin.process.computer.MapReduce$Stage.Static;
function autoImport(shortName: 'Memory'): Java.org.apache.tinkerpop.gremlin.process.computer.Memory.Static;
function autoImport(shortName: 'Memory$Admin'): Java.org.apache.tinkerpop.gremlin.process.computer.Memory$Admin.Static;
function autoImport(shortName: 'Memory$Exceptions'): Java.org.apache.tinkerpop.gremlin.process.computer.Memory$Exceptions.Static;
function autoImport(shortName: 'MessageCombiner'): Java.org.apache.tinkerpop.gremlin.process.computer.MessageCombiner.Static;
function autoImport(shortName: 'MessageScope'): Java.org.apache.tinkerpop.gremlin.process.computer.MessageScope.Static;
function autoImport(shortName: 'MessageScope$Global'): Java.org.apache.tinkerpop.gremlin.process.computer.MessageScope$Global.Static;
function autoImport(shortName: 'MessageScope$Local'): Java.org.apache.tinkerpop.gremlin.process.computer.MessageScope$Local.Static;
function autoImport(shortName: 'MessageScope$Local$ReverseTraversalSupplier'): Java.org.apache.tinkerpop.gremlin.process.computer.MessageScope$Local$ReverseTraversalSupplier.Static;
function autoImport(shortName: 'Messenger'): Java.org.apache.tinkerpop.gremlin.process.computer.Messenger.Static;
function autoImport(shortName: 'PageRankMapReduce'): Java.org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankMapReduce.Static;
function autoImport(shortName: 'PageRankMapReduce$Builder'): Java.org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankMapReduce$Builder.Static;
function autoImport(shortName: 'PageRankMessageCombiner'): Java.org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankMessageCombiner.Static;
function autoImport(shortName: 'PageRankVertexProgram'): Java.org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankVertexProgram.Static;
function autoImport(shortName: 'PageRankVertexProgram$Builder'): Java.org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankVertexProgram$Builder.Static;
function autoImport(shortName: 'SingleMessenger'): Java.org.apache.tinkerpop.gremlin.process.computer.traversal.SingleMessenger.Static;
function autoImport(shortName: 'TraversalClassSupplier'): Java.org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalClassSupplier.Static;
function autoImport(shortName: 'TraversalVertexProgram'): Java.org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalVertexProgram.Static;
function autoImport(shortName: 'TraversalVertexProgram$Builder'): Java.org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalVertexProgram$Builder.Static;
function autoImport(shortName: 'TraversalVertexProgramMessageCombiner'): Java.org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalVertexProgramMessageCombiner.Static;
function autoImport(shortName: 'TraverserExecutor'): Java.org.apache.tinkerpop.gremlin.process.computer.traversal.TraverserExecutor.Static;
function autoImport(shortName: 'VertexTraversalSideEffects'): Java.org.apache.tinkerpop.gremlin.process.computer.traversal.VertexTraversalSideEffects.Static;
function autoImport(shortName: 'VertexProgram'): Java.org.apache.tinkerpop.gremlin.process.computer.VertexProgram.Static;
function autoImport(shortName: 'VertexProgram$Builder'): Java.org.apache.tinkerpop.gremlin.process.computer.VertexProgram$Builder.Static;
function autoImport(shortName: 'VertexProgram$Features'): Java.org.apache.tinkerpop.gremlin.process.computer.VertexProgram$Features.Static;
function autoImport(shortName: 'Compare'): Java.org.apache.tinkerpop.gremlin.process.traversal.Compare.Static;
function autoImport(shortName: 'Contains'): Java.org.apache.tinkerpop.gremlin.process.traversal.Contains.Static;
function autoImport(shortName: '__'): Java.org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.__.Static;
function autoImport(shortName: 'DefaultGraphTraversal'): Java.org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.Static;
function autoImport(shortName: 'EmptyGraphTraversal'): Java.org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.EmptyGraphTraversal.Static;
function autoImport(shortName: 'GraphTraversal'): Java.org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal.Static;
function autoImport(shortName: 'GraphTraversal$Admin'): Java.org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$Admin.Static;
function autoImport(shortName: 'GraphTraversalSource'): Java.org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource.Static;
function autoImport(shortName: 'GraphTraversalSource$Builder'): Java.org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource$Builder.Static;
function autoImport(shortName: 'GraphTraversalSource$GraphTraversalSourceStub'): Java.org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource$GraphTraversalSourceStub.Static;
function autoImport(shortName: 'ComputerTraversalEngine'): Java.org.apache.tinkerpop.gremlin.process.traversal.engine.ComputerTraversalEngine.Static;
function autoImport(shortName: 'ComputerTraversalEngine$Builder'): Java.org.apache.tinkerpop.gremlin.process.traversal.engine.ComputerTraversalEngine$Builder.Static;
function autoImport(shortName: 'ComputerTraversalEngine$ComputerResultStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.engine.ComputerTraversalEngine$ComputerResultStrategy.Static;
function autoImport(shortName: 'StandardTraversalEngine'): Java.org.apache.tinkerpop.gremlin.process.traversal.engine.StandardTraversalEngine.Static;
function autoImport(shortName: 'StandardTraversalEngine$Builder'): Java.org.apache.tinkerpop.gremlin.process.traversal.engine.StandardTraversalEngine$Builder.Static;
function autoImport(shortName: 'Operator'): Java.org.apache.tinkerpop.gremlin.process.traversal.Operator.Static;
function autoImport(shortName: 'Order'): Java.org.apache.tinkerpop.gremlin.process.traversal.Order.Static;
function autoImport(shortName: 'P'): Java.org.apache.tinkerpop.gremlin.process.traversal.P.Static;
function autoImport(shortName: 'Path'): Java.org.apache.tinkerpop.gremlin.process.traversal.Path.Static;
function autoImport(shortName: 'Path$Exceptions'): Java.org.apache.tinkerpop.gremlin.process.traversal.Path$Exceptions.Static;
function autoImport(shortName: 'Scope'): Java.org.apache.tinkerpop.gremlin.process.traversal.Scope.Static;
function autoImport(shortName: 'Step'): Java.org.apache.tinkerpop.gremlin.process.traversal.Step.Static;
function autoImport(shortName: 'AbstractStep'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.Static;
function autoImport(shortName: 'BulkSet'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.BulkSet.Static;
function autoImport(shortName: 'CollectingBarrierStep'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.CollectingBarrierStep.Static;
function autoImport(shortName: 'ComputerAwareStep'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep.Static;
function autoImport(shortName: 'ComputerAwareStep$EndStep'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep$EndStep.Static;
function autoImport(shortName: 'ElementFunctionComparator'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.ElementFunctionComparator.Static;
function autoImport(shortName: 'ElementValueComparator'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.ElementValueComparator.Static;
function autoImport(shortName: 'EmptyPath'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.EmptyPath.Static;
function autoImport(shortName: 'EmptyStep'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.EmptyStep.Static;
function autoImport(shortName: 'ExpandableStepIterator'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.Static;
function autoImport(shortName: 'HasContainer'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.HasContainer.Static;
function autoImport(shortName: 'ImmutablePath'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.ImmutablePath.Static;
function autoImport(shortName: 'MapHelper'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.MapHelper.Static;
function autoImport(shortName: 'MutablePath'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.MutablePath.Static;
function autoImport(shortName: 'NoOpBarrierStep'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.NoOpBarrierStep.Static;
function autoImport(shortName: 'PathIdentityStep'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.PathIdentityStep.Static;
function autoImport(shortName: 'ReducingBarrierStep'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.Static;
function autoImport(shortName: 'ReducingBarrierStep$DefaultMapReduce'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep$DefaultMapReduce.Static;
function autoImport(shortName: 'ReducingBarrierStep$FinalGet'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep$FinalGet.Static;
function autoImport(shortName: 'SupplyingBarrierStep'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.SupplyingBarrierStep.Static;
function autoImport(shortName: 'TraversalComparator'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.TraversalComparator.Static;
function autoImport(shortName: 'Tree'): Java.org.apache.tinkerpop.gremlin.process.traversal.step.util.Tree.Static;
function autoImport(shortName: 'ConjunctionStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.ConjunctionStrategy.Static;
function autoImport(shortName: 'ElementIdStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.ElementIdStrategy.Static;
function autoImport(shortName: 'ElementIdStrategy$Builder'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.ElementIdStrategy$Builder.Static;
function autoImport(shortName: 'EventStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.EventStrategy.Static;
function autoImport(shortName: 'EventStrategy$Builder'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.EventStrategy$Builder.Static;
function autoImport(shortName: 'EventStrategy$EventStrategyCallback'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.EventStrategy$EventStrategyCallback.Static;
function autoImport(shortName: 'PartitionStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.PartitionStrategy.Static;
function autoImport(shortName: 'PartitionStrategy$Builder'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.PartitionStrategy$Builder.Static;
function autoImport(shortName: 'SubgraphStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategy.Static;
function autoImport(shortName: 'SubgraphStrategy$Builder'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategy$Builder.Static;
function autoImport(shortName: 'ComputerVerificationException'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.ComputerVerificationException.Static;
function autoImport(shortName: 'ComputerVerificationStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.ComputerVerificationStrategy.Static;
function autoImport(shortName: 'LambdaRestrictionStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.LambdaRestrictionStrategy.Static;
function autoImport(shortName: 'ReadOnlyStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.ReadOnlyStrategy.Static;
function autoImport(shortName: 'Traversal'): Java.org.apache.tinkerpop.gremlin.process.traversal.Traversal.Static;
function autoImport(shortName: 'Traversal$Admin'): Java.org.apache.tinkerpop.gremlin.process.traversal.Traversal$Admin.Static;
function autoImport(shortName: 'Traversal$Exceptions'): Java.org.apache.tinkerpop.gremlin.process.traversal.Traversal$Exceptions.Static;
function autoImport(shortName: 'TraversalEngine'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalEngine.Static;
function autoImport(shortName: 'TraversalEngine$Builder'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalEngine$Builder.Static;
function autoImport(shortName: 'TraversalEngine$Type'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalEngine$Type.Static;
function autoImport(shortName: 'TraversalSideEffects'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalSideEffects.Static;
function autoImport(shortName: 'TraversalSideEffects$Exceptions'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalSideEffects$Exceptions.Static;
function autoImport(shortName: 'TraversalSource'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalSource.Static;
function autoImport(shortName: 'TraversalSource$Builder'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalSource$Builder.Static;
function autoImport(shortName: 'TraversalStrategies'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies.Static;
function autoImport(shortName: 'TraversalStrategies$GlobalCache'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies$GlobalCache.Static;
function autoImport(shortName: 'TraversalStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy.Static;
function autoImport(shortName: 'TraversalStrategy$DecorationStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$DecorationStrategy.Static;
function autoImport(shortName: 'TraversalStrategy$FinalizationStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$FinalizationStrategy.Static;
function autoImport(shortName: 'TraversalStrategy$OptimizationStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$OptimizationStrategy.Static;
function autoImport(shortName: 'TraversalStrategy$VendorOptimizationStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$VendorOptimizationStrategy.Static;
function autoImport(shortName: 'TraversalStrategy$VerificationStrategy'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$VerificationStrategy.Static;
function autoImport(shortName: 'Traverser'): Java.org.apache.tinkerpop.gremlin.process.traversal.Traverser.Static;
function autoImport(shortName: 'Traverser$Admin'): Java.org.apache.tinkerpop.gremlin.process.traversal.Traverser$Admin.Static;
function autoImport(shortName: 'TraverserGenerator'): Java.org.apache.tinkerpop.gremlin.process.traversal.TraverserGenerator.Static;
function autoImport(shortName: 'AndP'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.AndP.Static;
function autoImport(shortName: 'ConjunctionP'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.ConjunctionP.Static;
function autoImport(shortName: 'DefaultTraversal'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.Static;
function autoImport(shortName: 'DefaultTraversalSideEffects'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalSideEffects.Static;
function autoImport(shortName: 'DefaultTraversalStrategies'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalStrategies.Static;
function autoImport(shortName: 'DependantMutableMetrics'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.DependantMutableMetrics.Static;
function autoImport(shortName: 'EmptyTraversal'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.EmptyTraversal.Static;
function autoImport(shortName: 'EmptyTraversalSideEffects'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.EmptyTraversalSideEffects.Static;
function autoImport(shortName: 'EmptyTraversalStrategies'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.EmptyTraversalStrategies.Static;
function autoImport(shortName: 'FastNoSuchElementException'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.FastNoSuchElementException.Static;
function autoImport(shortName: 'ImmutableMetrics'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.ImmutableMetrics.Static;
function autoImport(shortName: 'Metrics'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.Metrics.Static;
function autoImport(shortName: 'MutableMetrics'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.MutableMetrics.Static;
function autoImport(shortName: 'OrP'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.OrP.Static;
function autoImport(shortName: 'SideEffectHelper'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.SideEffectHelper.Static;
function autoImport(shortName: 'StandardTraversalMetrics'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.StandardTraversalMetrics.Static;
function autoImport(shortName: 'StepPosition'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.StepPosition.Static;
function autoImport(shortName: 'TraversalHelper'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalHelper.Static;
function autoImport(shortName: 'TraversalMatrix'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalMatrix.Static;
function autoImport(shortName: 'TraversalMetrics'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalMetrics.Static;
function autoImport(shortName: 'TraversalObjectFunction'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalObjectFunction.Static;
function autoImport(shortName: 'TraversalP'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalP.Static;
function autoImport(shortName: 'TraversalRing'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalRing.Static;
function autoImport(shortName: 'TraversalScriptFunction'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalScriptFunction.Static;
function autoImport(shortName: 'TraversalScriptHelper'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalScriptHelper.Static;
function autoImport(shortName: 'TraversalUtil'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.Static;
function autoImport(shortName: 'TraversalUtil$Multiple'): Java.org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil$Multiple.Static;
function autoImport(shortName: 'Direction'): Java.org.apache.tinkerpop.gremlin.structure.Direction.Static;
function autoImport(shortName: 'Edge'): Java.org.apache.tinkerpop.gremlin.structure.Edge.Static;
function autoImport(shortName: 'Edge$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.Edge$Exceptions.Static;
function autoImport(shortName: 'Element'): Java.org.apache.tinkerpop.gremlin.structure.Element.Static;
function autoImport(shortName: 'Element$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.Element$Exceptions.Static;
function autoImport(shortName: 'Graph'): Java.org.apache.tinkerpop.gremlin.structure.Graph.Static;
function autoImport(shortName: 'Graph$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Exceptions.Static;
function autoImport(shortName: 'Graph$Features'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features.Static;
function autoImport(shortName: 'Graph$Features$DataTypeFeatures'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$DataTypeFeatures.Static;
function autoImport(shortName: 'Graph$Features$EdgeFeatures'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$EdgeFeatures.Static;
function autoImport(shortName: 'Graph$Features$EdgePropertyFeatures'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$EdgePropertyFeatures.Static;
function autoImport(shortName: 'Graph$Features$ElementFeatures'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$ElementFeatures.Static;
function autoImport(shortName: 'Graph$Features$FeatureSet'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$FeatureSet.Static;
function autoImport(shortName: 'Graph$Features$GraphFeatures'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$GraphFeatures.Static;
function autoImport(shortName: 'Graph$Features$PropertyFeatures'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$PropertyFeatures.Static;
function autoImport(shortName: 'Graph$Features$VariableFeatures'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$VariableFeatures.Static;
function autoImport(shortName: 'Graph$Features$VertexFeatures'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$VertexFeatures.Static;
function autoImport(shortName: 'Graph$Features$VertexPropertyFeatures'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Features$VertexPropertyFeatures.Static;
function autoImport(shortName: 'Graph$Hidden'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Hidden.Static;
function autoImport(shortName: 'Graph$OptIn'): Java.org.apache.tinkerpop.gremlin.structure.Graph$OptIn.Static;
function autoImport(shortName: 'Graph$OptIns'): Java.org.apache.tinkerpop.gremlin.structure.Graph$OptIns.Static;
function autoImport(shortName: 'Graph$OptOut'): Java.org.apache.tinkerpop.gremlin.structure.Graph$OptOut.Static;
function autoImport(shortName: 'Graph$OptOuts'): Java.org.apache.tinkerpop.gremlin.structure.Graph$OptOuts.Static;
function autoImport(shortName: 'Graph$Variables'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Variables.Static;
function autoImport(shortName: 'Graph$Variables$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.Graph$Variables$Exceptions.Static;
function autoImport(shortName: 'AbstractIoRegistry'): Java.org.apache.tinkerpop.gremlin.structure.io.AbstractIoRegistry.Static;
function autoImport(shortName: 'GraphMigrator'): Java.org.apache.tinkerpop.gremlin.structure.io.GraphMigrator.Static;
function autoImport(shortName: 'GraphMLIo'): Java.org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLIo.Static;
function autoImport(shortName: 'GraphMLIo$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLIo$Builder.Static;
function autoImport(shortName: 'GraphMLMapper'): Java.org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLMapper.Static;
function autoImport(shortName: 'GraphMLMapper$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLMapper$Builder.Static;
function autoImport(shortName: 'GraphMLReader'): Java.org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLReader.Static;
function autoImport(shortName: 'GraphMLReader$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLReader$Builder.Static;
function autoImport(shortName: 'GraphMLWriter'): Java.org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLWriter.Static;
function autoImport(shortName: 'GraphMLWriter$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLWriter$Builder.Static;
function autoImport(shortName: 'GraphMLWriterHelper$IndentingXMLStreamWriter'): Java.org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLWriterHelper$IndentingXMLStreamWriter.Static;
function autoImport(shortName: 'GraphReader'): Java.org.apache.tinkerpop.gremlin.structure.io.GraphReader.Static;
function autoImport(shortName: 'GraphReader$ReaderBuilder'): Java.org.apache.tinkerpop.gremlin.structure.io.GraphReader$ReaderBuilder.Static;
function autoImport(shortName: 'GraphSONIo'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONIo.Static;
function autoImport(shortName: 'GraphSONIo$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONIo$Builder.Static;
function autoImport(shortName: 'GraphSONMapper'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONMapper.Static;
function autoImport(shortName: 'GraphSONMapper$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONMapper$Builder.Static;
function autoImport(shortName: 'GraphSONModule'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONModule.Static;
function autoImport(shortName: 'GraphSONReader'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader.Static;
function autoImport(shortName: 'GraphSONReader$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader$Builder.Static;
function autoImport(shortName: 'GraphSONTokens'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONTokens.Static;
function autoImport(shortName: 'GraphSONUtil'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.Static;
function autoImport(shortName: 'GraphSONWriter'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter.Static;
function autoImport(shortName: 'GraphSONWriter$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter$Builder.Static;
function autoImport(shortName: 'LegacyGraphSONReader'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.LegacyGraphSONReader.Static;
function autoImport(shortName: 'LegacyGraphSONReader$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.LegacyGraphSONReader$Builder.Static;
function autoImport(shortName: 'LegacyGraphSONReader$GraphSONTokens'): Java.org.apache.tinkerpop.gremlin.structure.io.graphson.LegacyGraphSONReader$GraphSONTokens.Static;
function autoImport(shortName: 'GraphWriter'): Java.org.apache.tinkerpop.gremlin.structure.io.GraphWriter.Static;
function autoImport(shortName: 'GraphWriter$WriterBuilder'): Java.org.apache.tinkerpop.gremlin.structure.io.GraphWriter$WriterBuilder.Static;
function autoImport(shortName: 'GryoIo'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoIo.Static;
function autoImport(shortName: 'GryoIo$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoIo$Builder.Static;
function autoImport(shortName: 'GryoMapper'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoMapper.Static;
function autoImport(shortName: 'GryoMapper$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoMapper$Builder.Static;
function autoImport(shortName: 'GryoPool'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoPool.Static;
function autoImport(shortName: 'GryoPool$Type'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoPool$Type.Static;
function autoImport(shortName: 'GryoReader'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoReader.Static;
function autoImport(shortName: 'GryoReader$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoReader$Builder.Static;
function autoImport(shortName: 'GryoWriter'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoWriter.Static;
function autoImport(shortName: 'GryoWriter$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.GryoWriter$Builder.Static;
function autoImport(shortName: 'VertexByteArrayInputStream'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.VertexByteArrayInputStream.Static;
function autoImport(shortName: 'VertexTerminator'): Java.org.apache.tinkerpop.gremlin.structure.io.gryo.VertexTerminator.Static;
function autoImport(shortName: 'Io'): Java.org.apache.tinkerpop.gremlin.structure.io.Io.Static;
function autoImport(shortName: 'Io$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.Io$Builder.Static;
function autoImport(shortName: 'Io$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.io.Io$Exceptions.Static;
function autoImport(shortName: 'IoCore'): Java.org.apache.tinkerpop.gremlin.structure.io.IoCore.Static;
function autoImport(shortName: 'IoRegistry'): Java.org.apache.tinkerpop.gremlin.structure.io.IoRegistry.Static;
function autoImport(shortName: 'Mapper'): Java.org.apache.tinkerpop.gremlin.structure.io.Mapper.Static;
function autoImport(shortName: 'Mapper$Builder'): Java.org.apache.tinkerpop.gremlin.structure.io.Mapper$Builder.Static;
function autoImport(shortName: 'Property'): Java.org.apache.tinkerpop.gremlin.structure.Property.Static;
function autoImport(shortName: 'Property$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.Property$Exceptions.Static;
function autoImport(shortName: 'PropertyType'): Java.org.apache.tinkerpop.gremlin.structure.PropertyType.Static;
function autoImport(shortName: 'T'): Java.org.apache.tinkerpop.gremlin.structure.T.Static;
function autoImport(shortName: 'Transaction'): Java.org.apache.tinkerpop.gremlin.structure.Transaction.Static;
function autoImport(shortName: 'Transaction$CLOSE_BEHAVIOR'): Java.org.apache.tinkerpop.gremlin.structure.Transaction$CLOSE_BEHAVIOR.Static;
function autoImport(shortName: 'Transaction$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.Transaction$Exceptions.Static;
function autoImport(shortName: 'Transaction$READ_WRITE_BEHAVIOR'): Java.org.apache.tinkerpop.gremlin.structure.Transaction$READ_WRITE_BEHAVIOR.Static;
function autoImport(shortName: 'Transaction$Status'): Java.org.apache.tinkerpop.gremlin.structure.Transaction$Status.Static;
function autoImport(shortName: 'Transaction$Workload'): Java.org.apache.tinkerpop.gremlin.structure.Transaction$Workload.Static;
function autoImport(shortName: 'AbstractTransaction'): Java.org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.Static;
function autoImport(shortName: 'AbstractTransaction$TransactionException'): Java.org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction$TransactionException.Static;
function autoImport(shortName: 'Attachable'): Java.org.apache.tinkerpop.gremlin.structure.util.Attachable.Static;
function autoImport(shortName: 'Attachable$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.util.Attachable$Exceptions.Static;
function autoImport(shortName: 'Attachable$Method'): Java.org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.Static;
function autoImport(shortName: 'Comparators'): Java.org.apache.tinkerpop.gremlin.structure.util.Comparators.Static;
function autoImport(shortName: 'DetachedEdge'): Java.org.apache.tinkerpop.gremlin.structure.util.detached.DetachedEdge.Static;
function autoImport(shortName: 'DetachedElement'): Java.org.apache.tinkerpop.gremlin.structure.util.detached.DetachedElement.Static;
function autoImport(shortName: 'DetachedFactory'): Java.org.apache.tinkerpop.gremlin.structure.util.detached.DetachedFactory.Static;
function autoImport(shortName: 'DetachedPath'): Java.org.apache.tinkerpop.gremlin.structure.util.detached.DetachedPath.Static;
function autoImport(shortName: 'DetachedProperty'): Java.org.apache.tinkerpop.gremlin.structure.util.detached.DetachedProperty.Static;
function autoImport(shortName: 'DetachedVertex'): Java.org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertex.Static;
function autoImport(shortName: 'DetachedVertexProperty'): Java.org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertexProperty.Static;
function autoImport(shortName: 'ElementHelper'): Java.org.apache.tinkerpop.gremlin.structure.util.ElementHelper.Static;
function autoImport(shortName: 'FeatureDescriptor'): Java.org.apache.tinkerpop.gremlin.structure.util.FeatureDescriptor.Static;
function autoImport(shortName: 'GraphFactory'): Java.org.apache.tinkerpop.gremlin.structure.util.GraphFactory.Static;
function autoImport(shortName: 'GraphVariableHelper'): Java.org.apache.tinkerpop.gremlin.structure.util.GraphVariableHelper.Static;
function autoImport(shortName: 'Host'): Java.org.apache.tinkerpop.gremlin.structure.util.Host.Static;
function autoImport(shortName: 'StringFactory'): Java.org.apache.tinkerpop.gremlin.structure.util.StringFactory.Static;
function autoImport(shortName: 'Vertex'): Java.org.apache.tinkerpop.gremlin.structure.Vertex.Static;
function autoImport(shortName: 'Vertex$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.Vertex$Exceptions.Static;
function autoImport(shortName: 'VertexProperty'): Java.org.apache.tinkerpop.gremlin.structure.VertexProperty.Static;
function autoImport(shortName: 'VertexProperty$Cardinality'): Java.org.apache.tinkerpop.gremlin.structure.VertexProperty$Cardinality.Static;
function autoImport(shortName: 'VertexProperty$Exceptions'): Java.org.apache.tinkerpop.gremlin.structure.VertexProperty$Exceptions.Static;
function autoImport(shortName: 'TinkerComputerResult'): Java.org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerComputerResult.Static;
function autoImport(shortName: 'TinkerGraphComputer'): Java.org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerGraphComputer.Static;
function autoImport(shortName: 'TinkerGraphView'): Java.org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerGraphView.Static;
function autoImport(shortName: 'TinkerMapEmitter'): Java.org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerMapEmitter.Static;
function autoImport(shortName: 'TinkerMemory'): Java.org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerMemory.Static;
function autoImport(shortName: 'TinkerMessenger'): Java.org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerMessenger.Static;
function autoImport(shortName: 'TinkerReduceEmitter'): Java.org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerReduceEmitter.Static;
function autoImport(shortName: 'TinkerWorkerPool'): Java.org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerWorkerPool.Static;
function autoImport(shortName: 'TinkerEdge'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerEdge.Static;
function autoImport(shortName: 'TinkerElement'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerElement.Static;
function autoImport(shortName: 'TinkerFactory'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerFactory.Static;
function autoImport(shortName: 'TinkerGraph'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph.Static;
function autoImport(shortName: 'TinkerGraph$DefaultIdManager'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$DefaultIdManager.Static;
function autoImport(shortName: 'TinkerGraph$IdManager'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$IdManager.Static;
function autoImport(shortName: 'TinkerGraph$TinkerGraphEdgeFeatures'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$TinkerGraphEdgeFeatures.Static;
function autoImport(shortName: 'TinkerGraph$TinkerGraphFeatures'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$TinkerGraphFeatures.Static;
function autoImport(shortName: 'TinkerGraph$TinkerGraphGraphFeatures'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$TinkerGraphGraphFeatures.Static;
function autoImport(shortName: 'TinkerGraph$TinkerGraphVertexFeatures'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$TinkerGraphVertexFeatures.Static;
function autoImport(shortName: 'TinkerGraphVariables'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraphVariables.Static;
function autoImport(shortName: 'TinkerHelper'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerHelper.Static;
function autoImport(shortName: 'TinkerProperty'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerProperty.Static;
function autoImport(shortName: 'TinkerVertex'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerVertex.Static;
function autoImport(shortName: 'TinkerVertexProperty'): Java.org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerVertexProperty.Static;
function autoImport(shortName: 'ArrayListSupplier'): Java.org.apache.tinkerpop.gremlin.util.function_.ArrayListSupplier.Static;
function autoImport(shortName: 'BulkSetSupplier'): Java.org.apache.tinkerpop.gremlin.util.function_.BulkSetSupplier.Static;
function autoImport(shortName: 'ChainedComparator'): Java.org.apache.tinkerpop.gremlin.util.function_.ChainedComparator.Static;
function autoImport(shortName: 'CloningUnaryOperator'): Java.org.apache.tinkerpop.gremlin.util.function_.CloningUnaryOperator.Static;
function autoImport(shortName: 'ConstantSupplier'): Java.org.apache.tinkerpop.gremlin.util.function_.ConstantSupplier.Static;
function autoImport(shortName: 'FunctionUtils'): Java.org.apache.tinkerpop.gremlin.util.function_.FunctionUtils.Static;
function autoImport(shortName: 'HashMapSupplier'): Java.org.apache.tinkerpop.gremlin.util.function_.HashMapSupplier.Static;
function autoImport(shortName: 'HashSetSupplier'): Java.org.apache.tinkerpop.gremlin.util.function_.HashSetSupplier.Static;
function autoImport(shortName: 'MeanNumberSupplier'): Java.org.apache.tinkerpop.gremlin.util.function_.MeanNumberSupplier.Static;
function autoImport(shortName: 'ScriptEngineLambda'): Java.org.apache.tinkerpop.gremlin.util.function_.ScriptEngineLambda.Static;
function autoImport(shortName: 'ThrowingBiConsumer'): Java.org.apache.tinkerpop.gremlin.util.function_.ThrowingBiConsumer.Static;
function autoImport(shortName: 'ThrowingConsumer'): Java.org.apache.tinkerpop.gremlin.util.function_.ThrowingConsumer.Static;
function autoImport(shortName: 'ThrowingFunction'): Java.org.apache.tinkerpop.gremlin.util.function_.ThrowingFunction.Static;
function autoImport(shortName: 'ThrowingSupplier'): Java.org.apache.tinkerpop.gremlin.util.function_.ThrowingSupplier.Static;
function autoImport(shortName: 'TraversableLambda'): Java.org.apache.tinkerpop.gremlin.util.function_.TraversableLambda.Static;
function autoImport(shortName: 'TreeSupplier'): Java.org.apache.tinkerpop.gremlin.util.function_.TreeSupplier.Static;
function autoImport(shortName: 'TriConsumer'): Java.org.apache.tinkerpop.gremlin.util.function_.TriConsumer.Static;
function autoImport(shortName: 'TriFunction'): Java.org.apache.tinkerpop.gremlin.util.function_.TriFunction.Static;
function autoImport(shortName: 'Gremlin'): Java.org.apache.tinkerpop.gremlin.util.Gremlin.Static;
function autoImport(shortName: 'InterruptedRuntimeException'): Java.org.apache.tinkerpop.gremlin.util.InterruptedRuntimeException.Static;
function autoImport(shortName: 'ScriptEngineCache'): Java.org.apache.tinkerpop.gremlin.util.ScriptEngineCache.Static;
function autoImport(shortName: 'Serializer'): Java.org.apache.tinkerpop.gremlin.util.Serializer.Static;
function autoImport(shortName: 'StreamFactory'): Java.org.apache.tinkerpop.gremlin.util.StreamFactory.Static;
function autoImport(shortName: 'TimeUtil'): Java.org.apache.tinkerpop.gremlin.util.TimeUtil.Static;
function autoImport(shortName: 'ClassNode'): Java.org.codehaus.groovy.ast.ClassNode.Static;
function autoImport(shortName: 'CompilerConfiguration'): Java.org.codehaus.groovy.control.CompilerConfiguration.Static;
function autoImport(shortName: 'CompilationCustomizer'): Java.org.codehaus.groovy.control.customizers.CompilationCustomizer.Static;
function autoImport(shortName: 'NullObject'): Java.org.codehaus.groovy.runtime.NullObject.Static;
function autoImport(shortName: 'Groovysh'): Java.org.codehaus.groovy.tools.shell.Groovysh.Static;
function autoImport(shortName: 'ManagedReference'): Java.org.codehaus.groovy.util.ManagedReference.Static;
function autoImport(shortName: 'ReferenceBundle'): Java.org.codehaus.groovy.util.ReferenceBundle.Static;
function autoImport(shortName: string): any;

function autoImport(shortName: string): any {

  var shortToLongNameMap: Dictionary = {
    'GlobFunction': 'co.redseal.gremlinnode.function.GlobFunction',
    'GroovyLambda': 'co.redseal.gremlinnode.function.GroovyLambda',
    'TestClass': 'co.redseal.gremlinnode.testing.TestClass',
    'StringInputStream': 'co.redseal.util.StringInputStream',
    'Binding': 'groovy.lang.Binding',
    'Closure': 'groovy.lang.Closure',
    'DelegatingMetaClass': 'groovy.lang.DelegatingMetaClass',
    'GroovyClassLoader': 'groovy.lang.GroovyClassLoader',
    'GroovyCodeSource': 'groovy.lang.GroovyCodeSource',
    'GroovyObjectSupport': 'groovy.lang.GroovyObjectSupport',
    'GroovyResourceLoader': 'groovy.lang.GroovyResourceLoader',
    'IntRange': 'groovy.lang.IntRange',
    'MetaBeanProperty': 'groovy.lang.MetaBeanProperty',
    'MetaClass': 'groovy.lang.MetaClass',
    'MetaMethod': 'groovy.lang.MetaMethod',
    'MetaProperty': 'groovy.lang.MetaProperty',
    'Range': 'groovy.lang.Range',
    'Reference': 'groovy.lang.Reference',
    'ByteArrayOutputStream': 'java.io.ByteArrayOutputStream',
    'FileInputStream': 'java.io.FileInputStream',
    'FileOutputStream': 'java.io.FileOutputStream',
    'InputStream': 'java.io.InputStream',
    'OutputStream': 'java.io.OutputStream',
    'Boolean': 'java.lang.Boolean',
    'Class': 'java.lang.Class',
    'ClassLoader': 'java.lang.ClassLoader',
    'Double': 'java.lang.Double',
    'Enum': 'java.lang.Enum',
    'Float': 'java.lang.Float',
    'Integer': 'java.lang.Integer',
    'Iterable': 'java.lang.Iterable',
    'Long': 'java.lang.Long',
    'Object': 'java.lang.Object',
    'Array': 'java.lang.reflect.Array',
    'Short': 'java.lang.Short',
    'String': 'java.lang.String',
    'Charset': 'java.nio.charset.Charset',
    'StandardCharsets': 'java.nio.charset.StandardCharsets',
    'AbstractCollection': 'java.util.AbstractCollection',
    'AbstractList': 'java.util.AbstractList',
    'AbstractMap': 'java.util.AbstractMap',
    'AbstractSet': 'java.util.AbstractSet',
    'ArrayList': 'java.util.ArrayList',
    'Collection': 'java.util.Collection',
    'Comparator': 'java.util.Comparator',
    'BiConsumer': 'java.util.function.BiConsumer',
    'BiFunction': 'java.util.function.BiFunction',
    'BinaryOperator': 'java.util.function.BinaryOperator',
    'BiPredicate': 'java.util.function.BiPredicate',
    'Consumer': 'java.util.function.Consumer',
    'Function': 'java.util.function.Function',
    'Predicate': 'java.util.function.Predicate',
    'Supplier': 'java.util.function.Supplier',
    'UnaryOperator': 'java.util.function.UnaryOperator',
    'HashMap': 'java.util.HashMap',
    'HashSet': 'java.util.HashSet',
    'Iterator': 'java.util.Iterator',
    'LinkedHashMap': 'java.util.LinkedHashMap',
    'List': 'java.util.List',
    'ListIterator': 'java.util.ListIterator',
    'Map': 'java.util.Map',
    'Map$Entry': 'java.util.Map$Entry',
    'NoSuchElementException': 'java.util.NoSuchElementException',
    'Set': 'java.util.Set',
    'AbstractScriptEngine': 'javax.script.AbstractScriptEngine',
    'Bindings': 'javax.script.Bindings',
    'CompiledScript': 'javax.script.CompiledScript',
    'ScriptContext': 'javax.script.ScriptContext',
    'ScriptEngine': 'javax.script.ScriptEngine',
    'ScriptEngineFactory': 'javax.script.ScriptEngineFactory',
    'GComparator': 'org.apache.tinkerpop.gremlin.groovy.function.GComparator',
    'GFunction': 'org.apache.tinkerpop.gremlin.groovy.function.GFunction',
    'GSupplier': 'org.apache.tinkerpop.gremlin.groovy.function.GSupplier',
    'GUnaryOperator': 'org.apache.tinkerpop.gremlin.groovy.function.GUnaryOperator',
    'GremlinGroovyScriptEngine': 'org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine',
    'ClusterCountMapReduce': 'org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.ClusterCountMapReduce',
    'ClusterCountMapReduce$Builder': 'org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.ClusterCountMapReduce$Builder',
    'ClusterPopulationMapReduce': 'org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.ClusterPopulationMapReduce',
    'ClusterPopulationMapReduce$Builder': 'org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.ClusterPopulationMapReduce$Builder',
    'PeerPressureVertexProgram': 'org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.PeerPressureVertexProgram',
    'PeerPressureVertexProgram$Builder': 'org.apache.tinkerpop.gremlin.process.computer.clustering.peerpressure.PeerPressureVertexProgram$Builder',
    'ComputerResult': 'org.apache.tinkerpop.gremlin.process.computer.ComputerResult',
    'GraphComputer': 'org.apache.tinkerpop.gremlin.process.computer.GraphComputer',
    'GraphComputer$Exceptions': 'org.apache.tinkerpop.gremlin.process.computer.GraphComputer$Exceptions',
    'GraphComputer$Features': 'org.apache.tinkerpop.gremlin.process.computer.GraphComputer$Features',
    'GraphComputer$Isolation': 'org.apache.tinkerpop.gremlin.process.computer.GraphComputer$Isolation',
    'GraphComputer$Persist': 'org.apache.tinkerpop.gremlin.process.computer.GraphComputer$Persist',
    'GraphComputer$ResultGraph': 'org.apache.tinkerpop.gremlin.process.computer.GraphComputer$ResultGraph',
    'KeyValue': 'org.apache.tinkerpop.gremlin.process.computer.KeyValue',
    'MapReduce': 'org.apache.tinkerpop.gremlin.process.computer.MapReduce',
    'MapReduce$MapEmitter': 'org.apache.tinkerpop.gremlin.process.computer.MapReduce$MapEmitter',
    'MapReduce$NullObject': 'org.apache.tinkerpop.gremlin.process.computer.MapReduce$NullObject',
    'MapReduce$ReduceEmitter': 'org.apache.tinkerpop.gremlin.process.computer.MapReduce$ReduceEmitter',
    'MapReduce$Stage': 'org.apache.tinkerpop.gremlin.process.computer.MapReduce$Stage',
    'Memory': 'org.apache.tinkerpop.gremlin.process.computer.Memory',
    'Memory$Admin': 'org.apache.tinkerpop.gremlin.process.computer.Memory$Admin',
    'Memory$Exceptions': 'org.apache.tinkerpop.gremlin.process.computer.Memory$Exceptions',
    'MessageCombiner': 'org.apache.tinkerpop.gremlin.process.computer.MessageCombiner',
    'MessageScope': 'org.apache.tinkerpop.gremlin.process.computer.MessageScope',
    'MessageScope$Global': 'org.apache.tinkerpop.gremlin.process.computer.MessageScope$Global',
    'MessageScope$Local': 'org.apache.tinkerpop.gremlin.process.computer.MessageScope$Local',
    'MessageScope$Local$ReverseTraversalSupplier': 'org.apache.tinkerpop.gremlin.process.computer.MessageScope$Local$ReverseTraversalSupplier',
    'Messenger': 'org.apache.tinkerpop.gremlin.process.computer.Messenger',
    'PageRankMapReduce': 'org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankMapReduce',
    'PageRankMapReduce$Builder': 'org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankMapReduce$Builder',
    'PageRankMessageCombiner': 'org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankMessageCombiner',
    'PageRankVertexProgram': 'org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankVertexProgram',
    'PageRankVertexProgram$Builder': 'org.apache.tinkerpop.gremlin.process.computer.ranking.pagerank.PageRankVertexProgram$Builder',
    'SingleMessenger': 'org.apache.tinkerpop.gremlin.process.computer.traversal.SingleMessenger',
    'TraversalClassSupplier': 'org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalClassSupplier',
    'TraversalVertexProgram': 'org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalVertexProgram',
    'TraversalVertexProgram$Builder': 'org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalVertexProgram$Builder',
    'TraversalVertexProgramMessageCombiner': 'org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalVertexProgramMessageCombiner',
    'TraverserExecutor': 'org.apache.tinkerpop.gremlin.process.computer.traversal.TraverserExecutor',
    'VertexTraversalSideEffects': 'org.apache.tinkerpop.gremlin.process.computer.traversal.VertexTraversalSideEffects',
    'VertexProgram': 'org.apache.tinkerpop.gremlin.process.computer.VertexProgram',
    'VertexProgram$Builder': 'org.apache.tinkerpop.gremlin.process.computer.VertexProgram$Builder',
    'VertexProgram$Features': 'org.apache.tinkerpop.gremlin.process.computer.VertexProgram$Features',
    'Compare': 'org.apache.tinkerpop.gremlin.process.traversal.Compare',
    'Contains': 'org.apache.tinkerpop.gremlin.process.traversal.Contains',
    '__': 'org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.__',
    'DefaultGraphTraversal': 'org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal',
    'EmptyGraphTraversal': 'org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.EmptyGraphTraversal',
    'GraphTraversal': 'org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal',
    'GraphTraversal$Admin': 'org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$Admin',
    'GraphTraversalSource': 'org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource',
    'GraphTraversalSource$Builder': 'org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource$Builder',
    'GraphTraversalSource$GraphTraversalSourceStub': 'org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource$GraphTraversalSourceStub',
    'ComputerTraversalEngine': 'org.apache.tinkerpop.gremlin.process.traversal.engine.ComputerTraversalEngine',
    'ComputerTraversalEngine$Builder': 'org.apache.tinkerpop.gremlin.process.traversal.engine.ComputerTraversalEngine$Builder',
    'ComputerTraversalEngine$ComputerResultStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.engine.ComputerTraversalEngine$ComputerResultStrategy',
    'StandardTraversalEngine': 'org.apache.tinkerpop.gremlin.process.traversal.engine.StandardTraversalEngine',
    'StandardTraversalEngine$Builder': 'org.apache.tinkerpop.gremlin.process.traversal.engine.StandardTraversalEngine$Builder',
    'Operator': 'org.apache.tinkerpop.gremlin.process.traversal.Operator',
    'Order': 'org.apache.tinkerpop.gremlin.process.traversal.Order',
    'P': 'org.apache.tinkerpop.gremlin.process.traversal.P',
    'Path': 'org.apache.tinkerpop.gremlin.process.traversal.Path',
    'Path$Exceptions': 'org.apache.tinkerpop.gremlin.process.traversal.Path$Exceptions',
    'Scope': 'org.apache.tinkerpop.gremlin.process.traversal.Scope',
    'Step': 'org.apache.tinkerpop.gremlin.process.traversal.Step',
    'AbstractStep': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep',
    'BulkSet': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.BulkSet',
    'CollectingBarrierStep': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.CollectingBarrierStep',
    'ComputerAwareStep': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep',
    'ComputerAwareStep$EndStep': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep$EndStep',
    'ElementFunctionComparator': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.ElementFunctionComparator',
    'ElementValueComparator': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.ElementValueComparator',
    'EmptyPath': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.EmptyPath',
    'EmptyStep': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.EmptyStep',
    'ExpandableStepIterator': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator',
    'HasContainer': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.HasContainer',
    'ImmutablePath': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.ImmutablePath',
    'MapHelper': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.MapHelper',
    'MutablePath': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.MutablePath',
    'NoOpBarrierStep': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.NoOpBarrierStep',
    'PathIdentityStep': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.PathIdentityStep',
    'ReducingBarrierStep': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep',
    'ReducingBarrierStep$DefaultMapReduce': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep$DefaultMapReduce',
    'ReducingBarrierStep$FinalGet': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep$FinalGet',
    'SupplyingBarrierStep': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.SupplyingBarrierStep',
    'TraversalComparator': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.TraversalComparator',
    'Tree': 'org.apache.tinkerpop.gremlin.process.traversal.step.util.Tree',
    'ConjunctionStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.ConjunctionStrategy',
    'ElementIdStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.ElementIdStrategy',
    'ElementIdStrategy$Builder': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.ElementIdStrategy$Builder',
    'EventStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.EventStrategy',
    'EventStrategy$Builder': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.EventStrategy$Builder',
    'EventStrategy$EventStrategyCallback': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.EventStrategy$EventStrategyCallback',
    'PartitionStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.PartitionStrategy',
    'PartitionStrategy$Builder': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.PartitionStrategy$Builder',
    'SubgraphStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategy',
    'SubgraphStrategy$Builder': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategy$Builder',
    'ComputerVerificationException': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.ComputerVerificationException',
    'ComputerVerificationStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.ComputerVerificationStrategy',
    'LambdaRestrictionStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.LambdaRestrictionStrategy',
    'ReadOnlyStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.ReadOnlyStrategy',
    'Traversal': 'org.apache.tinkerpop.gremlin.process.traversal.Traversal',
    'Traversal$Admin': 'org.apache.tinkerpop.gremlin.process.traversal.Traversal$Admin',
    'Traversal$Exceptions': 'org.apache.tinkerpop.gremlin.process.traversal.Traversal$Exceptions',
    'TraversalEngine': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalEngine',
    'TraversalEngine$Builder': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalEngine$Builder',
    'TraversalEngine$Type': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalEngine$Type',
    'TraversalSideEffects': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalSideEffects',
    'TraversalSideEffects$Exceptions': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalSideEffects$Exceptions',
    'TraversalSource': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalSource',
    'TraversalSource$Builder': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalSource$Builder',
    'TraversalStrategies': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies',
    'TraversalStrategies$GlobalCache': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies$GlobalCache',
    'TraversalStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy',
    'TraversalStrategy$DecorationStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$DecorationStrategy',
    'TraversalStrategy$FinalizationStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$FinalizationStrategy',
    'TraversalStrategy$OptimizationStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$OptimizationStrategy',
    'TraversalStrategy$VendorOptimizationStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$VendorOptimizationStrategy',
    'TraversalStrategy$VerificationStrategy': 'org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategy$VerificationStrategy',
    'Traverser': 'org.apache.tinkerpop.gremlin.process.traversal.Traverser',
    'Traverser$Admin': 'org.apache.tinkerpop.gremlin.process.traversal.Traverser$Admin',
    'TraverserGenerator': 'org.apache.tinkerpop.gremlin.process.traversal.TraverserGenerator',
    'AndP': 'org.apache.tinkerpop.gremlin.process.traversal.util.AndP',
    'ConjunctionP': 'org.apache.tinkerpop.gremlin.process.traversal.util.ConjunctionP',
    'DefaultTraversal': 'org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal',
    'DefaultTraversalSideEffects': 'org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalSideEffects',
    'DefaultTraversalStrategies': 'org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalStrategies',
    'DependantMutableMetrics': 'org.apache.tinkerpop.gremlin.process.traversal.util.DependantMutableMetrics',
    'EmptyTraversal': 'org.apache.tinkerpop.gremlin.process.traversal.util.EmptyTraversal',
    'EmptyTraversalSideEffects': 'org.apache.tinkerpop.gremlin.process.traversal.util.EmptyTraversalSideEffects',
    'EmptyTraversalStrategies': 'org.apache.tinkerpop.gremlin.process.traversal.util.EmptyTraversalStrategies',
    'FastNoSuchElementException': 'org.apache.tinkerpop.gremlin.process.traversal.util.FastNoSuchElementException',
    'ImmutableMetrics': 'org.apache.tinkerpop.gremlin.process.traversal.util.ImmutableMetrics',
    'Metrics': 'org.apache.tinkerpop.gremlin.process.traversal.util.Metrics',
    'MutableMetrics': 'org.apache.tinkerpop.gremlin.process.traversal.util.MutableMetrics',
    'OrP': 'org.apache.tinkerpop.gremlin.process.traversal.util.OrP',
    'SideEffectHelper': 'org.apache.tinkerpop.gremlin.process.traversal.util.SideEffectHelper',
    'StandardTraversalMetrics': 'org.apache.tinkerpop.gremlin.process.traversal.util.StandardTraversalMetrics',
    'StepPosition': 'org.apache.tinkerpop.gremlin.process.traversal.util.StepPosition',
    'TraversalHelper': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalHelper',
    'TraversalMatrix': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalMatrix',
    'TraversalMetrics': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalMetrics',
    'TraversalObjectFunction': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalObjectFunction',
    'TraversalP': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalP',
    'TraversalRing': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalRing',
    'TraversalScriptFunction': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalScriptFunction',
    'TraversalScriptHelper': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalScriptHelper',
    'TraversalUtil': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil',
    'TraversalUtil$Multiple': 'org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil$Multiple',
    'Direction': 'org.apache.tinkerpop.gremlin.structure.Direction',
    'Edge': 'org.apache.tinkerpop.gremlin.structure.Edge',
    'Edge$Exceptions': 'org.apache.tinkerpop.gremlin.structure.Edge$Exceptions',
    'Element': 'org.apache.tinkerpop.gremlin.structure.Element',
    'Element$Exceptions': 'org.apache.tinkerpop.gremlin.structure.Element$Exceptions',
    'Graph': 'org.apache.tinkerpop.gremlin.structure.Graph',
    'Graph$Exceptions': 'org.apache.tinkerpop.gremlin.structure.Graph$Exceptions',
    'Graph$Features': 'org.apache.tinkerpop.gremlin.structure.Graph$Features',
    'Graph$Features$DataTypeFeatures': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$DataTypeFeatures',
    'Graph$Features$EdgeFeatures': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$EdgeFeatures',
    'Graph$Features$EdgePropertyFeatures': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$EdgePropertyFeatures',
    'Graph$Features$ElementFeatures': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$ElementFeatures',
    'Graph$Features$FeatureSet': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$FeatureSet',
    'Graph$Features$GraphFeatures': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$GraphFeatures',
    'Graph$Features$PropertyFeatures': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$PropertyFeatures',
    'Graph$Features$VariableFeatures': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$VariableFeatures',
    'Graph$Features$VertexFeatures': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$VertexFeatures',
    'Graph$Features$VertexPropertyFeatures': 'org.apache.tinkerpop.gremlin.structure.Graph$Features$VertexPropertyFeatures',
    'Graph$Hidden': 'org.apache.tinkerpop.gremlin.structure.Graph$Hidden',
    'Graph$OptIn': 'org.apache.tinkerpop.gremlin.structure.Graph$OptIn',
    'Graph$OptIns': 'org.apache.tinkerpop.gremlin.structure.Graph$OptIns',
    'Graph$OptOut': 'org.apache.tinkerpop.gremlin.structure.Graph$OptOut',
    'Graph$OptOuts': 'org.apache.tinkerpop.gremlin.structure.Graph$OptOuts',
    'Graph$Variables': 'org.apache.tinkerpop.gremlin.structure.Graph$Variables',
    'Graph$Variables$Exceptions': 'org.apache.tinkerpop.gremlin.structure.Graph$Variables$Exceptions',
    'AbstractIoRegistry': 'org.apache.tinkerpop.gremlin.structure.io.AbstractIoRegistry',
    'GraphMigrator': 'org.apache.tinkerpop.gremlin.structure.io.GraphMigrator',
    'GraphMLIo': 'org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLIo',
    'GraphMLIo$Builder': 'org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLIo$Builder',
    'GraphMLMapper': 'org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLMapper',
    'GraphMLMapper$Builder': 'org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLMapper$Builder',
    'GraphMLReader': 'org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLReader',
    'GraphMLReader$Builder': 'org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLReader$Builder',
    'GraphMLWriter': 'org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLWriter',
    'GraphMLWriter$Builder': 'org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLWriter$Builder',
    'GraphMLWriterHelper$IndentingXMLStreamWriter': 'org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLWriterHelper$IndentingXMLStreamWriter',
    'GraphReader': 'org.apache.tinkerpop.gremlin.structure.io.GraphReader',
    'GraphReader$ReaderBuilder': 'org.apache.tinkerpop.gremlin.structure.io.GraphReader$ReaderBuilder',
    'GraphSONIo': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONIo',
    'GraphSONIo$Builder': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONIo$Builder',
    'GraphSONMapper': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONMapper',
    'GraphSONMapper$Builder': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONMapper$Builder',
    'GraphSONModule': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONModule',
    'GraphSONReader': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader',
    'GraphSONReader$Builder': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader$Builder',
    'GraphSONTokens': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONTokens',
    'GraphSONUtil': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil',
    'GraphSONWriter': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter',
    'GraphSONWriter$Builder': 'org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter$Builder',
    'LegacyGraphSONReader': 'org.apache.tinkerpop.gremlin.structure.io.graphson.LegacyGraphSONReader',
    'LegacyGraphSONReader$Builder': 'org.apache.tinkerpop.gremlin.structure.io.graphson.LegacyGraphSONReader$Builder',
    'LegacyGraphSONReader$GraphSONTokens': 'org.apache.tinkerpop.gremlin.structure.io.graphson.LegacyGraphSONReader$GraphSONTokens',
    'GraphWriter': 'org.apache.tinkerpop.gremlin.structure.io.GraphWriter',
    'GraphWriter$WriterBuilder': 'org.apache.tinkerpop.gremlin.structure.io.GraphWriter$WriterBuilder',
    'GryoIo': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoIo',
    'GryoIo$Builder': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoIo$Builder',
    'GryoMapper': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoMapper',
    'GryoMapper$Builder': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoMapper$Builder',
    'GryoPool': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoPool',
    'GryoPool$Type': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoPool$Type',
    'GryoReader': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoReader',
    'GryoReader$Builder': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoReader$Builder',
    'GryoWriter': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoWriter',
    'GryoWriter$Builder': 'org.apache.tinkerpop.gremlin.structure.io.gryo.GryoWriter$Builder',
    'VertexByteArrayInputStream': 'org.apache.tinkerpop.gremlin.structure.io.gryo.VertexByteArrayInputStream',
    'VertexTerminator': 'org.apache.tinkerpop.gremlin.structure.io.gryo.VertexTerminator',
    'Io': 'org.apache.tinkerpop.gremlin.structure.io.Io',
    'Io$Builder': 'org.apache.tinkerpop.gremlin.structure.io.Io$Builder',
    'Io$Exceptions': 'org.apache.tinkerpop.gremlin.structure.io.Io$Exceptions',
    'IoCore': 'org.apache.tinkerpop.gremlin.structure.io.IoCore',
    'IoRegistry': 'org.apache.tinkerpop.gremlin.structure.io.IoRegistry',
    'Mapper': 'org.apache.tinkerpop.gremlin.structure.io.Mapper',
    'Mapper$Builder': 'org.apache.tinkerpop.gremlin.structure.io.Mapper$Builder',
    'Property': 'org.apache.tinkerpop.gremlin.structure.Property',
    'Property$Exceptions': 'org.apache.tinkerpop.gremlin.structure.Property$Exceptions',
    'PropertyType': 'org.apache.tinkerpop.gremlin.structure.PropertyType',
    'T': 'org.apache.tinkerpop.gremlin.structure.T',
    'Transaction': 'org.apache.tinkerpop.gremlin.structure.Transaction',
    'Transaction$CLOSE_BEHAVIOR': 'org.apache.tinkerpop.gremlin.structure.Transaction$CLOSE_BEHAVIOR',
    'Transaction$Exceptions': 'org.apache.tinkerpop.gremlin.structure.Transaction$Exceptions',
    'Transaction$READ_WRITE_BEHAVIOR': 'org.apache.tinkerpop.gremlin.structure.Transaction$READ_WRITE_BEHAVIOR',
    'Transaction$Status': 'org.apache.tinkerpop.gremlin.structure.Transaction$Status',
    'Transaction$Workload': 'org.apache.tinkerpop.gremlin.structure.Transaction$Workload',
    'AbstractTransaction': 'org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction',
    'AbstractTransaction$TransactionException': 'org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction$TransactionException',
    'Attachable': 'org.apache.tinkerpop.gremlin.structure.util.Attachable',
    'Attachable$Exceptions': 'org.apache.tinkerpop.gremlin.structure.util.Attachable$Exceptions',
    'Attachable$Method': 'org.apache.tinkerpop.gremlin.structure.util.Attachable$Method',
    'Comparators': 'org.apache.tinkerpop.gremlin.structure.util.Comparators',
    'DetachedEdge': 'org.apache.tinkerpop.gremlin.structure.util.detached.DetachedEdge',
    'DetachedElement': 'org.apache.tinkerpop.gremlin.structure.util.detached.DetachedElement',
    'DetachedFactory': 'org.apache.tinkerpop.gremlin.structure.util.detached.DetachedFactory',
    'DetachedPath': 'org.apache.tinkerpop.gremlin.structure.util.detached.DetachedPath',
    'DetachedProperty': 'org.apache.tinkerpop.gremlin.structure.util.detached.DetachedProperty',
    'DetachedVertex': 'org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertex',
    'DetachedVertexProperty': 'org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertexProperty',
    'ElementHelper': 'org.apache.tinkerpop.gremlin.structure.util.ElementHelper',
    'FeatureDescriptor': 'org.apache.tinkerpop.gremlin.structure.util.FeatureDescriptor',
    'GraphFactory': 'org.apache.tinkerpop.gremlin.structure.util.GraphFactory',
    'GraphVariableHelper': 'org.apache.tinkerpop.gremlin.structure.util.GraphVariableHelper',
    'Host': 'org.apache.tinkerpop.gremlin.structure.util.Host',
    'StringFactory': 'org.apache.tinkerpop.gremlin.structure.util.StringFactory',
    'Vertex': 'org.apache.tinkerpop.gremlin.structure.Vertex',
    'Vertex$Exceptions': 'org.apache.tinkerpop.gremlin.structure.Vertex$Exceptions',
    'VertexProperty': 'org.apache.tinkerpop.gremlin.structure.VertexProperty',
    'VertexProperty$Cardinality': 'org.apache.tinkerpop.gremlin.structure.VertexProperty$Cardinality',
    'VertexProperty$Exceptions': 'org.apache.tinkerpop.gremlin.structure.VertexProperty$Exceptions',
    'TinkerComputerResult': 'org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerComputerResult',
    'TinkerGraphComputer': 'org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerGraphComputer',
    'TinkerGraphView': 'org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerGraphView',
    'TinkerMapEmitter': 'org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerMapEmitter',
    'TinkerMemory': 'org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerMemory',
    'TinkerMessenger': 'org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerMessenger',
    'TinkerReduceEmitter': 'org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerReduceEmitter',
    'TinkerWorkerPool': 'org.apache.tinkerpop.gremlin.tinkergraph.process.computer.TinkerWorkerPool',
    'TinkerEdge': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerEdge',
    'TinkerElement': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerElement',
    'TinkerFactory': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerFactory',
    'TinkerGraph': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph',
    'TinkerGraph$DefaultIdManager': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$DefaultIdManager',
    'TinkerGraph$IdManager': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$IdManager',
    'TinkerGraph$TinkerGraphEdgeFeatures': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$TinkerGraphEdgeFeatures',
    'TinkerGraph$TinkerGraphFeatures': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$TinkerGraphFeatures',
    'TinkerGraph$TinkerGraphGraphFeatures': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$TinkerGraphGraphFeatures',
    'TinkerGraph$TinkerGraphVertexFeatures': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph$TinkerGraphVertexFeatures',
    'TinkerGraphVariables': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraphVariables',
    'TinkerHelper': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerHelper',
    'TinkerProperty': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerProperty',
    'TinkerVertex': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerVertex',
    'TinkerVertexProperty': 'org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerVertexProperty',
    'ArrayListSupplier': 'org.apache.tinkerpop.gremlin.util.function.ArrayListSupplier',
    'BulkSetSupplier': 'org.apache.tinkerpop.gremlin.util.function.BulkSetSupplier',
    'ChainedComparator': 'org.apache.tinkerpop.gremlin.util.function.ChainedComparator',
    'CloningUnaryOperator': 'org.apache.tinkerpop.gremlin.util.function.CloningUnaryOperator',
    'ConstantSupplier': 'org.apache.tinkerpop.gremlin.util.function.ConstantSupplier',
    'FunctionUtils': 'org.apache.tinkerpop.gremlin.util.function.FunctionUtils',
    'HashMapSupplier': 'org.apache.tinkerpop.gremlin.util.function.HashMapSupplier',
    'HashSetSupplier': 'org.apache.tinkerpop.gremlin.util.function.HashSetSupplier',
    'MeanNumberSupplier': 'org.apache.tinkerpop.gremlin.util.function.MeanNumberSupplier',
    'ScriptEngineLambda': 'org.apache.tinkerpop.gremlin.util.function.ScriptEngineLambda',
    'ThrowingBiConsumer': 'org.apache.tinkerpop.gremlin.util.function.ThrowingBiConsumer',
    'ThrowingConsumer': 'org.apache.tinkerpop.gremlin.util.function.ThrowingConsumer',
    'ThrowingFunction': 'org.apache.tinkerpop.gremlin.util.function.ThrowingFunction',
    'ThrowingSupplier': 'org.apache.tinkerpop.gremlin.util.function.ThrowingSupplier',
    'TraversableLambda': 'org.apache.tinkerpop.gremlin.util.function.TraversableLambda',
    'TreeSupplier': 'org.apache.tinkerpop.gremlin.util.function.TreeSupplier',
    'TriConsumer': 'org.apache.tinkerpop.gremlin.util.function.TriConsumer',
    'TriFunction': 'org.apache.tinkerpop.gremlin.util.function.TriFunction',
    'Gremlin': 'org.apache.tinkerpop.gremlin.util.Gremlin',
    'InterruptedRuntimeException': 'org.apache.tinkerpop.gremlin.util.InterruptedRuntimeException',
    'ScriptEngineCache': 'org.apache.tinkerpop.gremlin.util.ScriptEngineCache',
    'Serializer': 'org.apache.tinkerpop.gremlin.util.Serializer',
    'StreamFactory': 'org.apache.tinkerpop.gremlin.util.StreamFactory',
    'TimeUtil': 'org.apache.tinkerpop.gremlin.util.TimeUtil',
    'ClassNode': 'org.codehaus.groovy.ast.ClassNode',
    'CompilerConfiguration': 'org.codehaus.groovy.control.CompilerConfiguration',
    'CompilationCustomizer': 'org.codehaus.groovy.control.customizers.CompilationCustomizer',
    'NullObject': 'org.codehaus.groovy.runtime.NullObject',
    'Groovysh': 'org.codehaus.groovy.tools.shell.Groovysh',
    'ManagedReference': 'org.codehaus.groovy.util.ManagedReference',
    'ReferenceBundle': 'org.codehaus.groovy.util.ReferenceBundle'
  };

  if (shortName in shortToLongNameMap) {
    return java.import(shortToLongNameMap[shortName]);
  } else {
    throw new Error('autoImport unable to import short name:' + shortName);
  }
}
